_wandb:
    value:
        cli_version: 0.23.0
        e:
            j9186sn9lyq7gt13zif8v0q9mhqjaykt:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "9663676416"
                codePath: src/train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "222925791232"
                email: shekkari@umd.edu
                executable: /Users/akhilshekkari/Desktop/DiffusionSR/.venv/bin/python
                git:
                    commit: 7a74ffb2428ac211aeddc7b9c20609d506b1e7b3
                    remote: https://github.com/shekkari1999/DiffusionSR.git
                host: Akhils-Laptop.local
                memory:
                    total: "8589934592"
                os: macOS-26.0.1-arm64-arm-64bit
                program: /Users/akhilshekkari/Desktop/DiffusionSR/src/train.py
                python: CPython 3.11.13
                root: /Users/akhilshekkari/Desktop/DiffusionSR/src
                startedAt: "2025-11-17T18:39:11.833490Z"
                writerId: j9186sn9lyq7gt13zif8v0q9mhqjaykt
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 1
                - 2
                - 13
                - 16
            "4": 3.11.13
            "5": 0.23.0
            "12": 0.23.0
            "13": darwin-arm64
T:
    value: 15
batch_size:
    value: 2
betas:
    value:
        - 0.9
        - 0.999
criterion:
    value: MSE
device:
    value: cpu
grad_clip:
    value: 1
k:
    value: 2
learning_rate:
    value: 5e-05
model:
    value: ResShift
optimizer:
    value: Adam
steps:
    value: 3
training_space:
    value: latent_64x64
